-- Sonic Search catalog enrichment: Ignez / hypnotic techno.
-- User-requested artist addition from Instagram handle @ignez__ with Somov Records context.

begin;

create temporary table hypnotic_techno_ignez_v1_tracks (
  style text not null,
  artist text not null,
  song text not null,
  label text,
  bpm_exact numeric,
  preview_url text,
  release_date date,
  duration_sec integer,
  country text,
  city text,
  artist_bio text,
  artist_genre text,
  artist_profile_hint text,
  source_url text,
  track_url text,
  deezer_track_id text,
  deezer_track_url text,
  cover_art_url text,
  youtube_track_url text,
  soundcloud_track_url text,
  bandcamp_track_url text,
  bandcamp_track_id text,
  label_links text,
  social_discovery_links text,
  source_tags text,
  album_keywords text,
  energy_band text,
  catalog_role text,
  status text,
  confidence text,
  source_note text
) on commit drop;

insert into hypnotic_techno_ignez_v1_tracks (
  style, artist, song, label, bpm_exact, preview_url, release_date, duration_sec, country, city,
  artist_bio, artist_genre, artist_profile_hint, source_url, track_url, deezer_track_id,
  deezer_track_url, cover_art_url, youtube_track_url, soundcloud_track_url, bandcamp_track_url,
  bandcamp_track_id, label_links, social_discovery_links, source_tags, album_keywords,
  energy_band, catalog_role, status, confidence, source_note
) values
('hypnotic_techno', 'Ignez', 'Us In The Sand', 'Somov Records', null, null, '2026-06-19', 348, 'Netherlands', 'Berlin', 'Ignez is a Dutch-born, Berlin-based DJ and producer behind Somov Records, with a tight hypnotic techno sound shaped by coastal atmosphere, minimal repetition and driving club pressure.', 'Hypnotic Techno / Deep Techno / Minimal Techno', 'Use Ignez when the listener wants hypnotic, driving and minimal techno with organic texture, slow-burn tension and controlled warehouse pressure.', 'https://somovrecords.bandcamp.com/album/smv017', 'https://www.deezer.com/track/4033281631', '4033281631', 'https://www.deezer.com/track/4033281631', 'https://cdn-images.dzcdn.net/images/cover/27e1d3c16c2556e9fafb9135ab2951e4/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/watch?v=xPJtMGrB8jo', null, 'https://somovrecords.bandcamp.com/track/us-in-the-sand', null, 'https://somovrecords.bandcamp.com/music;https://www.somovrecords.com;https://www.instagram.com/somov_records;https://soundcloud.com/somov-records', 'https://www.instagram.com/ignez__;https://soundcloud.com/ignez_smv;https://linktr.ee/ignez_;https://ra.co/dj/ignez;https://www.discogs.com/artist/7614467-Ignez;https://open.spotify.com/artist/35vEDafV45d7QN0D5rRwYV;https://music.apple.com/us/artist/ignez/1500008780;https://www.youtube.com/channel/UCciNzjuG3rNOKXfoX-IJC7g;https://tiktok.com/@ignez___', 'hypnotic_techno;deep_techno;minimal_techno;driving_techno;organic_techno;somov_records;dutch_techno;berlin_techno;recommended_artist', 'Us In The Sand;SMV017;Somov Records;Ignez;hypnotic techno;deep techno', 'hypnotic_driving', 'user_requested_anchor', 'published', 'high', 'User-requested addition. Instagram snapshot supplied by user: somov @somov_records; us in the sand -</3; ignez.co. Cross-checked with official Linktree, SoundCloud, RA, Discogs, Bandcamp/Somov and Deezer. Deezer id gives playable preview refresh; direct preview URLs are intentionally left blank to avoid stale signed links.'),
('hypnotic_techno', 'Ignez', 'Lunfardo', 'Somov Records', null, null, '2026-03-27', 386, 'Netherlands', 'Berlin', 'Ignez is a Dutch-born, Berlin-based DJ and producer behind Somov Records, with a tight hypnotic techno sound shaped by coastal atmosphere, minimal repetition and driving club pressure.', 'Hypnotic Techno / Deep Techno / Minimal Techno', 'Use Ignez when the listener wants hypnotic, driving and minimal techno with organic texture, slow-burn tension and controlled warehouse pressure.', 'https://www.deezer.com/track/3849107131', 'https://www.deezer.com/track/3849107131', '3849107131', 'https://www.deezer.com/track/3849107131', 'https://cdn-images.dzcdn.net/images/cover/e2cc7f218239997f0d365902cfded78e/1000x1000-000000-80-0-0.jpg', null, null, null, null, 'https://somovrecords.bandcamp.com/music;https://www.somovrecords.com;https://www.instagram.com/somov_records;https://soundcloud.com/somov-records', 'https://www.instagram.com/ignez__;https://soundcloud.com/ignez_smv;https://linktr.ee/ignez_;https://ra.co/dj/ignez;https://www.discogs.com/artist/7614467-Ignez;https://open.spotify.com/artist/35vEDafV45d7QN0D5rRwYV;https://music.apple.com/us/artist/ignez/1500008780;https://www.youtube.com/channel/UCciNzjuG3rNOKXfoX-IJC7g;https://tiktok.com/@ignez___', 'hypnotic_techno;deep_techno;minimal_techno;driving_techno;organic_techno;somov_records;dutch_techno;berlin_techno;recommended_artist', 'Lunfardo;SMV015;Somov Records;Ignez;hypnotic techno;minimal techno', 'minimal_hypnotic', 'hypnotic_depth_anchor', 'published', 'high', 'User-requested Ignez depth pick. Deezer release date is used for the catalog row; Discogs-style sources may list nearby physical release dates for SMV015.'),
('hypnotic_techno', 'Ignez', 'Immersion', 'Somov Records', null, null, '2025-06-13', 380, 'Netherlands', 'Berlin', 'Ignez is a Dutch-born, Berlin-based DJ and producer behind Somov Records, with a tight hypnotic techno sound shaped by coastal atmosphere, minimal repetition and driving club pressure.', 'Hypnotic Techno / Deep Techno / Minimal Techno', 'Use Ignez when the listener wants hypnotic, driving and minimal techno with organic texture, slow-burn tension and controlled warehouse pressure.', 'https://www.deezer.com/track/3346471611', 'https://www.deezer.com/track/3346471611', '3346471611', 'https://www.deezer.com/track/3346471611', 'https://cdn-images.dzcdn.net/images/cover/fba92395dca6ac4bb9c947ae08e555a0/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/watch?v=Y1fhM8CrYig', null, null, null, 'https://somovrecords.bandcamp.com/music;https://www.somovrecords.com;https://www.instagram.com/somov_records;https://soundcloud.com/somov-records', 'https://www.instagram.com/ignez__;https://soundcloud.com/ignez_smv;https://linktr.ee/ignez_;https://ra.co/dj/ignez;https://www.discogs.com/artist/7614467-Ignez;https://open.spotify.com/artist/35vEDafV45d7QN0D5rRwYV;https://music.apple.com/us/artist/ignez/1500008780;https://www.youtube.com/channel/UCciNzjuG3rNOKXfoX-IJC7g;https://tiktok.com/@ignez___', 'hypnotic_techno;deep_techno;minimal_techno;driving_techno;organic_techno;somov_records;dutch_techno;berlin_techno;recommended_artist', 'Immersion;SMV011;Somov Records;Ignez;deep techno;hypnotic techno', 'immersive_deep_pressure', 'somov_depth', 'published', 'high', 'Exact Deezer artist/track match with official YouTube upload signal; useful as a deeper Somov Records recommendation anchor.'),
('hypnotic_techno', 'Ignez', 'Lightworker', 'Somov Records', null, null, '2024-09-06', 354, 'Netherlands', 'Berlin', 'Ignez is a Dutch-born, Berlin-based DJ and producer behind Somov Records, with a tight hypnotic techno sound shaped by coastal atmosphere, minimal repetition and driving club pressure.', 'Hypnotic Techno / Deep Techno / Minimal Techno', 'Use Ignez when the listener wants hypnotic, driving and minimal techno with organic texture, slow-burn tension and controlled warehouse pressure.', 'https://www.deezer.com/track/2948834531', 'https://www.deezer.com/track/2948834531', '2948834531', 'https://www.deezer.com/track/2948834531', 'https://cdn-images.dzcdn.net/images/cover/41ef92f9df35c0bb9439d80a9dc5a179/1000x1000-000000-80-0-0.jpg', null, null, null, null, 'https://somovrecords.bandcamp.com/music;https://www.somovrecords.com;https://www.instagram.com/somov_records;https://soundcloud.com/somov-records', 'https://www.instagram.com/ignez__;https://soundcloud.com/ignez_smv;https://linktr.ee/ignez_;https://ra.co/dj/ignez;https://www.discogs.com/artist/7614467-Ignez;https://open.spotify.com/artist/35vEDafV45d7QN0D5rRwYV;https://music.apple.com/us/artist/ignez/1500008780;https://www.youtube.com/channel/UCciNzjuG3rNOKXfoX-IJC7g;https://tiktok.com/@ignez___', 'hypnotic_techno;deep_techno;minimal_techno;driving_techno;organic_techno;somov_records;dutch_techno;berlin_techno;recommended_artist', 'Lightworker;SMV010;Somov Records;Ignez;hypnotic techno;mental techno', 'mental_drive', 'somov_depth', 'published', 'high', 'Exact Deezer artist/track match; added to keep Ignez recommendations from overfitting only to the latest release.'),
('hypnotic_techno', 'Ignez', 'Skies We Share', 'Somov Records', null, null, '2025-06-13', 351, 'Netherlands', 'Berlin', 'Ignez is a Dutch-born, Berlin-based DJ and producer behind Somov Records, with a tight hypnotic techno sound shaped by coastal atmosphere, minimal repetition and driving club pressure.', 'Hypnotic Techno / Deep Techno / Minimal Techno', 'Use Ignez when the listener wants hypnotic, driving and minimal techno with organic texture, slow-burn tension and controlled warehouse pressure.', 'https://www.deezer.com/track/3346471621', 'https://www.deezer.com/track/3346471621', '3346471621', 'https://www.deezer.com/track/3346471621', 'https://cdn-images.dzcdn.net/images/cover/fba92395dca6ac4bb9c947ae08e555a0/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/watch?v=zQwKRQYn56s', null, null, null, 'https://somovrecords.bandcamp.com/music;https://www.somovrecords.com;https://www.instagram.com/somov_records;https://soundcloud.com/somov-records', 'https://www.instagram.com/ignez__;https://soundcloud.com/ignez_smv;https://linktr.ee/ignez_;https://ra.co/dj/ignez;https://www.discogs.com/artist/7614467-Ignez;https://open.spotify.com/artist/35vEDafV45d7QN0D5rRwYV;https://music.apple.com/us/artist/ignez/1500008780;https://www.youtube.com/channel/UCciNzjuG3rNOKXfoX-IJC7g;https://tiktok.com/@ignez___', 'hypnotic_techno;deep_techno;minimal_techno;driving_techno;organic_techno;somov_records;dutch_techno;berlin_techno;recommended_artist', 'Skies We Share;SMV011;Somov Records;Ignez;hypnotic techno;atmospheric techno', 'atmospheric_drive', 'somov_depth', 'published', 'high', 'Exact Deezer artist/track match with official YouTube upload signal; use as atmospheric hypnotic-techno depth around Ignez.');

insert into public.catalog_artists as catalog_artists (
  style,
  artist,
  country,
  city,
  artist_bio,
  artist_genre,
  artist_profile_hint,
  source,
  source_url,
  status,
  metadata
)
select distinct on (style, artist)
  style,
  artist,
  country,
  city,
  artist_bio,
  artist_genre,
  artist_profile_hint,
  'hypnotic_techno_ignez_enrichment_v1_20260705',
  'https://linktr.ee/ignez_',
  status,
  jsonb_strip_nulls(jsonb_build_object(
    'batch', 'hypnotic_techno_ignez_enrichment_v1_20260705',
    'confidence', confidence,
    'recommended', true,
    'recommendation_priority', 'user_requested_artist',
    'subgenre_primary', 'hypnotic_techno',
    'subgenre_secondary', array['deep_techno', 'minimal_techno', 'driving_techno', 'organic_techno'],
    'source_tags', case when coalesce(source_tags, '') = '' then array[]::text[] else string_to_array(source_tags, ';') end,
    'album_keywords', case when coalesce(album_keywords, '') = '' then array[]::text[] else string_to_array(album_keywords, ';') end,
    'label_links', case when coalesce(label_links, '') = '' then array[]::text[] else string_to_array(label_links, ';') end,
    'social_discovery_links', case when coalesce(social_discovery_links, '') = '' then array[]::text[] else string_to_array(social_discovery_links, ';') end,
    'artist_instagram_handle', '@ignez__',
    'artist_instagram_url', 'https://www.instagram.com/ignez__',
    'artist_tiktok_url', 'https://tiktok.com/@ignez___',
    'artist_youtube_url', 'https://www.youtube.com/channel/UCciNzjuG3rNOKXfoX-IJC7g',
    'artist_soundcloud_url', 'https://soundcloud.com/ignez_smv',
    'artist_spotify_url', 'https://open.spotify.com/artist/35vEDafV45d7QN0D5rRwYV',
    'artist_apple_music_url', 'https://music.apple.com/us/artist/ignez/1500008780',
    'artist_ra_url', 'https://ra.co/dj/ignez',
    'artist_discogs_url', 'https://www.discogs.com/artist/7614467-Ignez',
    'artist_deezer_id', '86525062',
    'musicbrainz_artist_id', 'd6a0d008-2ad1-4f35-b71e-dc386e636496',
    'label_name', 'Somov Records',
    'instagram_bio_snapshot', 'somov @somov_records; us in the sand -</3; ignez.co',
    'energy_band', energy_band,
    'catalog_role', catalog_role,
    'cover_art_url', cover_art_url,
    'deezer_track_id', deezer_track_id,
    'deezer_track_url', deezer_track_url,
    'youtube_track_url', youtube_track_url,
    'soundcloud_track_url', soundcloud_track_url,
    'bandcamp_track_url', bandcamp_track_url,
    'source_note', source_note
  ))
from hypnotic_techno_ignez_v1_tracks
order by style, artist, confidence desc, release_date desc
on conflict (style, artist_key) do update set
  country = coalesce(excluded.country, catalog_artists.country),
  city = coalesce(excluded.city, catalog_artists.city),
  artist_bio = excluded.artist_bio,
  artist_genre = excluded.artist_genre,
  artist_profile_hint = excluded.artist_profile_hint,
  source = excluded.source,
  source_url = excluded.source_url,
  status = excluded.status,
  metadata = coalesce(catalog_artists.metadata, '{}'::jsonb) || excluded.metadata,
  updated_at = now();

insert into public.catalog_tracks as catalog_tracks (
  style,
  artist,
  song,
  label,
  bpm_exact,
  preview_url,
  release_date,
  duration_sec,
  country,
  city,
  artist_bio,
  artist_genre,
  artist_profile_hint,
  source,
  source_url,
  status,
  metadata
)
select
  style,
  artist,
  song,
  label,
  bpm_exact,
  preview_url,
  release_date,
  duration_sec,
  country,
  city,
  artist_bio,
  artist_genre,
  artist_profile_hint,
  'hypnotic_techno_ignez_enrichment_v1_20260705',
  track_url,
  status,
  jsonb_strip_nulls(jsonb_build_object(
    'batch', 'hypnotic_techno_ignez_enrichment_v1_20260705',
    'confidence', confidence,
    'recommended', true,
    'recommendation_priority', case when catalog_role = 'user_requested_anchor' then 'user_requested_anchor' else 'artist_depth' end,
    'deezer_track_id', deezer_track_id,
    'deezer_track_url', deezer_track_url,
    'cover_art_url', cover_art_url,
    'youtube_track_url', youtube_track_url,
    'soundcloud_track_url', soundcloud_track_url,
    'bandcamp_track_url', bandcamp_track_url,
    'bandcamp_track_id', bandcamp_track_id,
    'track_url', track_url,
    'label_links', case when coalesce(label_links, '') = '' then array[]::text[] else string_to_array(label_links, ';') end,
    'social_discovery_links', case when coalesce(social_discovery_links, '') = '' then array[]::text[] else string_to_array(social_discovery_links, ';') end,
    'source_tags', case when coalesce(source_tags, '') = '' then array[]::text[] else string_to_array(source_tags, ';') end,
    'album_keywords', case when coalesce(album_keywords, '') = '' then array[]::text[] else string_to_array(album_keywords, ';') end,
    'energy_band', energy_band,
    'catalog_role', catalog_role,
    'artist_instagram_url', 'https://www.instagram.com/ignez__',
    'artist_soundcloud_url', 'https://soundcloud.com/ignez_smv',
    'artist_linktree_url', 'https://linktr.ee/ignez_',
    'artist_deezer_id', '86525062',
    'label_name', 'Somov Records',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['deezer_preview_refresh'],
    'source_note', source_note
  ))
from hypnotic_techno_ignez_v1_tracks
on conflict (style, track_key) do update set
  label = excluded.label,
  bpm_exact = excluded.bpm_exact,
  preview_url = excluded.preview_url,
  release_date = excluded.release_date,
  duration_sec = coalesce(excluded.duration_sec, catalog_tracks.duration_sec),
  country = coalesce(excluded.country, catalog_tracks.country),
  city = coalesce(excluded.city, catalog_tracks.city),
  artist_bio = excluded.artist_bio,
  artist_genre = excluded.artist_genre,
  artist_profile_hint = excluded.artist_profile_hint,
  source = excluded.source,
  source_url = excluded.source_url,
  status = excluded.status,
  metadata = coalesce(catalog_tracks.metadata, '{}'::jsonb) || excluded.metadata,
  updated_at = now();

commit;
