-- Sonic Search - Moonclipse / Astrix techno-related project focus.
-- Generated 2026-06-22.
-- Run after supabase/migrations/20260619024500_catalog_extra.sql.

insert into public.catalog_artists as catalog_artists (
  style,
  artist,
  country,
  city,
  artist_bio,
  artist_genre,
  artist_profile_hint,
  source,
  source_url,
  status,
  metadata
) values
(
  'melodic_techno',
  'Moonclipse',
  null,
  null,
  'Moonclipse is the melodic techno and house project of Omri Sasi and Avi Shmailov aka Astrix.',
  'melodic techno / melodic house / progressive house',
  'Use Moonclipse for Astrix-related techno recommendations; keep Astrix itself in psytrance/progressive/full-on.',
  'moonclipse_astrix_techno_project_20260622',
  'https://shamanictales.com/artists/moonclipse/',
  'published',
  jsonb_build_object(
    'batch', 'moonclipse_astrix_techno_project_20260622',
    'source_file', 'data/moonclipse_astrix_techno_project_20260622.csv',
    'confidence', 'high',
    'related_artist', 'Astrix',
    'related_artist_real_name', 'Avi Shmailov',
    'collaborator', 'Omri Sasi',
    'source_tags', array['melodic_techno', 'melodic_house', 'progressive_house', 'techno', 'moonclipse', 'astrix', 'avi_shmailov', 'omri_sasi', 'shamanic_tales'],
    'catalog_role', 'astrix_techno_project_anchor',
    'classification_guard', 'Do not reclassify Astrix itself as techno; use Moonclipse for the melodic techno/house project.'
  )
)
on conflict (style, artist_key) do update set
  country = coalesce(excluded.country, catalog_artists.country),
  city = coalesce(excluded.city, catalog_artists.city),
  artist_bio = coalesce(excluded.artist_bio, catalog_artists.artist_bio),
  artist_genre = coalesce(excluded.artist_genre, catalog_artists.artist_genre),
  artist_profile_hint = coalesce(excluded.artist_profile_hint, catalog_artists.artist_profile_hint),
  source = excluded.source,
  source_url = coalesce(excluded.source_url, catalog_artists.source_url),
  status = case when catalog_artists.status = 'hidden' then catalog_artists.status else excluded.status end,
  metadata = coalesce(catalog_artists.metadata, '{}'::jsonb) || excluded.metadata,
  updated_at = now();

insert into public.catalog_tracks as catalog_tracks (
  style,
  artist,
  song,
  label,
  bpm_exact,
  preview_url,
  release_date,
  duration_sec,
  country,
  city,
  artist_bio,
  artist_genre,
  artist_profile_hint,
  source,
  source_url,
  status,
  metadata
) values
(
  'melodic_techno',
  'Moonclipse',
  'Deep Distance',
  'Shamanic Tales',
  null,
  'https://cdnt-preview.dzcdn.net/api/1/1/4/b/5/0/4b577f49011bd6d427fda70fefe6cd31.mp3?hdnea=exp=1782109715~acl=/api/1/1/4/b/5/0/4b577f49011bd6d427fda70fefe6cd31.mp3*~data=user_id=0,application_id=42~hmac=c35f84f3b670505490f821f60219d6e66c37b0f53f1e1ec2709d5f812bfffa9e',
  '2022-11-18',
  523,
  null,
  null,
  'Moonclipse is the melodic techno and house project of Omri Sasi and Avi Shmailov aka Astrix.',
  'melodic techno / melodic house / progressive house',
  'Use Moonclipse for Astrix-related techno recommendations; keep Astrix itself in psytrance/progressive/full-on.',
  'moonclipse_astrix_techno_project_20260622',
  'https://www.deezer.com/track/1992222237',
  'published',
  jsonb_build_object(
    'batch', 'moonclipse_astrix_techno_project_20260622',
    'source_file', 'data/moonclipse_astrix_techno_project_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['audio_preview', 'deezer_preview_refresh'],
    'deezer_track_id', '1992222237',
    'deezer_track_url', 'https://www.deezer.com/track/1992222237',
    'cover_art_url', 'https://cdn-images.dzcdn.net/images/cover/0b316be78479607fccc48ad35e7033bd/500x500-000000-80-0-0.jpg',
    'source_tags', array['melodic_techno', 'melodic_house', 'progressive_house', 'techno', 'moonclipse', 'astrix', 'avi_shmailov', 'omri_sasi', 'shamanic_tales'],
    'catalog_role', 'astrix_techno_project_anchor',
    'confidence', 'high'
  )
),
(
  'melodic_techno',
  'Moonclipse',
  'Dunya',
  'Shamanic Tales',
  null,
  'https://cdnt-preview.dzcdn.net/api/1/1/7/7/a/0/77a5c685949d11652d499881cbbeee92.mp3?hdnea=exp=1782109715~acl=/api/1/1/7/7/a/0/77a5c685949d11652d499881cbbeee92.mp3*~data=user_id=0,application_id=42~hmac=4d0396ace79ecf616c41e272519b1a15a2bf2fbb099d55e2faf388e2f86dfedc',
  '2022-11-18',
  437,
  null,
  null,
  'Moonclipse is the melodic techno and house project of Omri Sasi and Avi Shmailov aka Astrix.',
  'melodic techno / melodic house / progressive house',
  'Use Moonclipse for Astrix-related techno recommendations; keep Astrix itself in psytrance/progressive/full-on.',
  'moonclipse_astrix_techno_project_20260622',
  'https://www.deezer.com/track/1992222247',
  'published',
  jsonb_build_object(
    'batch', 'moonclipse_astrix_techno_project_20260622',
    'source_file', 'data/moonclipse_astrix_techno_project_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['audio_preview', 'deezer_preview_refresh'],
    'deezer_track_id', '1992222247',
    'deezer_track_url', 'https://www.deezer.com/track/1992222247',
    'cover_art_url', 'https://cdn-images.dzcdn.net/images/cover/0b316be78479607fccc48ad35e7033bd/500x500-000000-80-0-0.jpg',
    'source_tags', array['melodic_techno', 'melodic_house', 'progressive_house', 'techno', 'moonclipse', 'astrix', 'avi_shmailov', 'omri_sasi', 'shamanic_tales'],
    'catalog_role', 'astrix_techno_project_anchor',
    'confidence', 'high'
  )
),
(
  'melodic_techno',
  'Moonclipse',
  'Endless',
  'Shamanic Tales',
  null,
  'https://cdnt-preview.dzcdn.net/api/1/1/7/b/c/0/7bc95593811b877478bdecfe1d7ac32b.mp3?hdnea=exp=1782109715~acl=/api/1/1/7/b/c/0/7bc95593811b877478bdecfe1d7ac32b.mp3*~data=user_id=0,application_id=42~hmac=40ed2252efb52a60b0df1fdf3c1ce35f015170b6d474b44cd01cb46cf1f9e40f',
  '2023-03-13',
  488,
  null,
  null,
  'Moonclipse is the melodic techno and house project of Omri Sasi and Avi Shmailov aka Astrix.',
  'melodic techno / melodic house / progressive house',
  'Use Moonclipse for Astrix-related techno recommendations; keep Astrix itself in psytrance/progressive/full-on.',
  'moonclipse_astrix_techno_project_20260622',
  'https://www.deezer.com/track/2167334497',
  'published',
  jsonb_build_object(
    'batch', 'moonclipse_astrix_techno_project_20260622',
    'source_file', 'data/moonclipse_astrix_techno_project_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['audio_preview', 'deezer_preview_refresh'],
    'deezer_track_id', '2167334497',
    'deezer_track_url', 'https://www.deezer.com/track/2167334497',
    'cover_art_url', 'https://cdn-images.dzcdn.net/images/cover/bec83c40b6551bf9cd926f1cf949e045/500x500-000000-80-0-0.jpg',
    'source_tags', array['melodic_techno', 'melodic_house', 'progressive_house', 'techno', 'moonclipse', 'astrix', 'avi_shmailov', 'omri_sasi', 'shamanic_tales'],
    'catalog_role', 'astrix_techno_project_anchor',
    'confidence', 'high'
  )
),
(
  'melodic_techno',
  'Moonclipse',
  'Heaven to Hell',
  'Shamanic Tales',
  null,
  'https://cdnt-preview.dzcdn.net/api/1/1/3/5/1/0/351702229147b138c04e641199a09d53.mp3?hdnea=exp=1782109715~acl=/api/1/1/3/5/1/0/351702229147b138c04e641199a09d53.mp3*~data=user_id=0,application_id=42~hmac=6d4b17ea618f6227deb5575b73f2df56b8282fe80c3910c7619d2a4d5c583484',
  '2023-03-13',
  481,
  null,
  null,
  'Moonclipse is the melodic techno and house project of Omri Sasi and Avi Shmailov aka Astrix.',
  'melodic techno / melodic house / progressive house',
  'Use Moonclipse for Astrix-related techno recommendations; keep Astrix itself in psytrance/progressive/full-on.',
  'moonclipse_astrix_techno_project_20260622',
  'https://www.deezer.com/track/2167334507',
  'published',
  jsonb_build_object(
    'batch', 'moonclipse_astrix_techno_project_20260622',
    'source_file', 'data/moonclipse_astrix_techno_project_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['audio_preview', 'deezer_preview_refresh'],
    'deezer_track_id', '2167334507',
    'deezer_track_url', 'https://www.deezer.com/track/2167334507',
    'cover_art_url', 'https://cdn-images.dzcdn.net/images/cover/bec83c40b6551bf9cd926f1cf949e045/500x500-000000-80-0-0.jpg',
    'source_tags', array['melodic_techno', 'melodic_house', 'progressive_house', 'techno', 'moonclipse', 'astrix', 'avi_shmailov', 'omri_sasi', 'shamanic_tales'],
    'catalog_role', 'astrix_techno_project_anchor',
    'confidence', 'high'
  )
),
(
  'melodic_techno',
  'Moonclipse',
  'Doux',
  'Shamanic Tales',
  null,
  'https://cdnt-preview.dzcdn.net/api/1/1/b/b/4/0/bb4fddcee31dfaecef46cad3c7d2d44e.mp3?hdnea=exp=1782109740~acl=/api/1/1/b/b/4/0/bb4fddcee31dfaecef46cad3c7d2d44e.mp3*~data=user_id=0,application_id=42~hmac=927e3b228349b512e4357a2832bf70024069e10e4fe0829cf57e816bc596cc37',
  '2024-03-25',
  424,
  null,
  null,
  'Moonclipse is the melodic techno and house project of Omri Sasi and Avi Shmailov aka Astrix.',
  'melodic techno / melodic house / progressive house',
  'Use Moonclipse for Astrix-related techno recommendations; keep Astrix itself in psytrance/progressive/full-on.',
  'moonclipse_astrix_techno_project_20260622',
  'https://www.deezer.com/track/2692227762',
  'published',
  jsonb_build_object(
    'batch', 'moonclipse_astrix_techno_project_20260622',
    'source_file', 'data/moonclipse_astrix_techno_project_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['audio_preview', 'deezer_preview_refresh'],
    'deezer_track_id', '2692227762',
    'deezer_track_url', 'https://www.deezer.com/track/2692227762',
    'cover_art_url', 'https://cdn-images.dzcdn.net/images/cover/d7ab2a2fdaef6570b1cda62c46f57a4a/500x500-000000-80-0-0.jpg',
    'source_tags', array['melodic_techno', 'melodic_house', 'progressive_house', 'techno', 'moonclipse', 'astrix', 'avi_shmailov', 'omri_sasi', 'shamanic_tales'],
    'catalog_role', 'astrix_techno_project_anchor',
    'confidence', 'high'
  )
),
(
  'melodic_techno',
  'Moonclipse',
  'Moments',
  'Shamanic Tales',
  null,
  'https://cdnt-preview.dzcdn.net/api/1/1/a/f/e/0/afe183b8140672ee0e5e4b534062bfcc.mp3?hdnea=exp=1782109740~acl=/api/1/1/a/f/e/0/afe183b8140672ee0e5e4b534062bfcc.mp3*~data=user_id=0,application_id=42~hmac=a3380c984f837d59dd2df660d2c63de48e42ad4335ee42d6fd1ffbe720c93273',
  '2023-06-19',
  489,
  null,
  null,
  'Moonclipse is the melodic techno and house project of Omri Sasi and Avi Shmailov aka Astrix.',
  'melodic techno / melodic house / progressive house',
  'Use Moonclipse for Astrix-related techno recommendations; keep Astrix itself in psytrance/progressive/full-on.',
  'moonclipse_astrix_techno_project_20260622',
  'https://www.deezer.com/track/2306721575',
  'published',
  jsonb_build_object(
    'batch', 'moonclipse_astrix_techno_project_20260622',
    'source_file', 'data/moonclipse_astrix_techno_project_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['audio_preview', 'deezer_preview_refresh'],
    'deezer_track_id', '2306721575',
    'deezer_track_url', 'https://www.deezer.com/track/2306721575',
    'cover_art_url', 'https://cdn-images.dzcdn.net/images/cover/cb81a7c05c2a6de9462f42b48f75a4c2/500x500-000000-80-0-0.jpg',
    'source_tags', array['melodic_techno', 'melodic_house', 'progressive_house', 'techno', 'moonclipse', 'astrix', 'avi_shmailov', 'omri_sasi', 'shamanic_tales'],
    'catalog_role', 'astrix_techno_project_anchor',
    'confidence', 'high'
  )
)
on conflict (style, track_key) do update set
  label = coalesce(excluded.label, catalog_tracks.label),
  bpm_exact = coalesce(excluded.bpm_exact, catalog_tracks.bpm_exact),
  preview_url = coalesce(excluded.preview_url, catalog_tracks.preview_url),
  release_date = coalesce(excluded.release_date, catalog_tracks.release_date),
  duration_sec = coalesce(excluded.duration_sec, catalog_tracks.duration_sec),
  country = coalesce(excluded.country, catalog_tracks.country),
  city = coalesce(excluded.city, catalog_tracks.city),
  artist_bio = coalesce(excluded.artist_bio, catalog_tracks.artist_bio),
  artist_genre = coalesce(excluded.artist_genre, catalog_tracks.artist_genre),
  artist_profile_hint = coalesce(excluded.artist_profile_hint, catalog_tracks.artist_profile_hint),
  source = excluded.source,
  source_url = coalesce(excluded.source_url, catalog_tracks.source_url),
  status = case when catalog_tracks.status = 'hidden' then catalog_tracks.status else excluded.status end,
  metadata = coalesce(catalog_tracks.metadata, '{}'::jsonb) || excluded.metadata,
  updated_at = now();
