-- Sonic Search catalog enrichment: Mattik / UK Garage bridge.
-- Conservative mapping: 2-step garage remains a metadata tag and maps to the existing uk_garage style.

begin;

create temporary table uk_garage_mattik_bridge_v1_tracks (
  style text not null,
  artist text not null,
  song text not null,
  label text,
  bpm_exact numeric,
  preview_url text,
  release_date date,
  duration_sec integer,
  country text,
  city text,
  artist_bio text,
  artist_genre text,
  artist_profile_hint text,
  source_url text,
  track_url text,
  deezer_track_id text,
  deezer_track_url text,
  cover_art_url text,
  youtube_track_url text,
  soundcloud_track_url text,
  bandcamp_track_url text,
  bandcamp_track_id text,
  label_links text,
  social_discovery_links text,
  source_tags text,
  album_keywords text,
  energy_band text,
  catalog_role text,
  status text,
  confidence text,
  source_note text
) on commit drop;

insert into uk_garage_mattik_bridge_v1_tracks (
  style, artist, song, label, bpm_exact, preview_url, release_date, duration_sec, country, city,
  artist_bio, artist_genre, artist_profile_hint, source_url, track_url, deezer_track_id,
  deezer_track_url, cover_art_url, youtube_track_url, soundcloud_track_url, bandcamp_track_url,
  bandcamp_track_id, label_links, social_discovery_links, source_tags, album_keywords,
  energy_band, catalog_role, status, confidence, source_note
) values
('uk_garage', 'Mattik', 'Bubble', 'INSTINCT', 138, null, '2025-03-28', 340, 'United Kingdom', 'Manchester', 'Mattik is a Manchester-linked UK club producer useful for modern UK Garage, 2-step and bassline discovery.', 'UK Garage / 2-step garage / bassline', 'Use Mattik when the listener wants swinging UKG drums, elastic low end and a modern underground garage feel.', 'https://www.beatport.com/track/bubble/20306208', 'https://www.deezer.com/track/3295843651', '3295843651', 'https://www.deezer.com/track/3295843651', 'https://cdn-images.dzcdn.net/images/cover/48fd6198a97e6ebc9792ca836f969b67/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Mattik+Bubble', null, 'https://mattikmusic.bandcamp.com/track/bubble-ep-instinct-click-link-in-bio', null, 'https://instinctrecs.bandcamp.com;https://www.discogs.com/label/1600703-Instinct-11', 'https://mattikmusic.bandcamp.com;https://soundcloud.com/search?q=Mattik;https://www.instagram.com/explore/search/keyword/?q=Mattik', 'uk_garage;2_step_garage;bassline;breakbeat_influence;tech_house_influence;mattik_anchor;instinct_i033', 'Bubble;INSTINCT;I033;UK Garage;2-step;bassline;Mattik', 'swinging_bassline_peak', 'mattik_anchor', 'published', 'high', 'User-discovered anchor. Beatport/Juno/Discogs evidence maps Bubble to UK Garage/Bassline; Beatport lists 138 BPM. Deezer id gives playable refresh path.'),
('uk_garage', 'Mattik', 'Systemattik', 'INSTINCT', null, null, '2024-02-02', 329, 'United Kingdom', 'Manchester', 'Mattik is a Manchester-linked UK club producer useful for modern UK Garage, 2-step and bassline discovery.', 'UK Garage / 2-step garage / bassline', 'Use Mattik when the listener wants swinging UKG drums, elastic low end and a modern underground garage feel.', 'https://mattikmusic.bandcamp.com/track/bubble-ep-instinct-click-link-in-bio', 'https://www.deezer.com/track/2662061052', '2662061052', 'https://www.deezer.com/track/2662061052', 'https://cdn-images.dzcdn.net/images/cover/c0bb51f5915c92066ce226fd823485da/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Mattik+Systemattik', null, 'https://mattikmusic.bandcamp.com/track/bubble-ep-instinct-click-link-in-bio', null, 'https://instinctrecs.bandcamp.com;https://www.discogs.com/label/1600703-Instinct-11', 'https://mattikmusic.bandcamp.com;https://soundcloud.com/search?q=Mattik;https://www.instagram.com/explore/search/keyword/?q=Mattik', 'uk_garage;2_step_garage;bassline;mattik_depth;instinct_i033', 'Systemattik;Bubble EP;INSTINCT;Mattik;UK Garage', 'rolling_ukg_bass', 'mattik_depth', 'published', 'medium_high', 'Exact Deezer artist/track match; kept as Mattik depth around the Bubble/Instinct context.'),
('bassline', 'Mattik', 'Active (featuring Charlie Boy Manson)', 'INSTINCT', null, null, '2025-03-28', 279, 'United Kingdom', 'Manchester', 'Mattik is a Manchester-linked UK club producer useful for modern UK Garage, 2-step and bassline discovery.', 'UK Garage / 2-step garage / bassline', 'Use Mattik when the listener wants swinging UKG drums, elastic low end and a modern underground garage feel.', 'https://mattikmusic.bandcamp.com/track/bubble-ep-instinct-click-link-in-bio', 'https://www.deezer.com/track/3295843671', '3295843671', 'https://www.deezer.com/track/3295843671', 'https://cdn-images.dzcdn.net/images/cover/48fd6198a97e6ebc9792ca836f969b67/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Mattik+Active+%28featuring+Charlie+Boy+Manson%29', null, 'https://mattikmusic.bandcamp.com/track/bubble-ep-instinct-click-link-in-bio', null, 'https://instinctrecs.bandcamp.com;https://www.discogs.com/label/1600703-Instinct-11', 'https://mattikmusic.bandcamp.com;https://soundcloud.com/search?q=Mattik;https://www.instagram.com/explore/search/keyword/?q=Mattik', 'bassline;uk_garage;2_step_garage;mattik_depth;instinct_i033', 'Active;Charlie Boy Manson;Bubble;INSTINCT;Mattik', 'bassline_pressure', 'mattik_depth', 'published', 'medium_high', 'Exact Deezer artist/track match; maps the Bubble EP into bassline-heavy recommendations.'),
('bassline', 'Mattik', 'Megatone Saxon (Manchester Massive)', 'INSTINCT', null, null, '2025-03-28', 289, 'United Kingdom', 'Manchester', 'Mattik is a Manchester-linked UK club producer useful for modern UK Garage, 2-step and bassline discovery.', 'UK Garage / 2-step garage / bassline', 'Use Mattik when the listener wants swinging UKG drums, elastic low end and a modern underground garage feel.', 'https://mattikmusic.bandcamp.com/track/bubble-ep-instinct-click-link-in-bio', 'https://www.deezer.com/track/3295843681', '3295843681', 'https://www.deezer.com/track/3295843681', 'https://cdn-images.dzcdn.net/images/cover/48fd6198a97e6ebc9792ca836f969b67/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Mattik+Megatone+Saxon+%28Manchester+Massive%29', null, 'https://mattikmusic.bandcamp.com/track/bubble-ep-instinct-click-link-in-bio', null, 'https://instinctrecs.bandcamp.com;https://www.discogs.com/label/1600703-Instinct-11', 'https://mattikmusic.bandcamp.com;https://soundcloud.com/search?q=Mattik;https://www.instagram.com/explore/search/keyword/?q=Mattik', 'bassline;uk_garage;2_step_garage;mattik_depth;manchester;instinct_i033', 'Megatone Saxon;Manchester Massive;Bubble;INSTINCT;Mattik', 'bassline_pressure', 'mattik_depth', 'published', 'medium_high', 'Exact Deezer artist/track match; useful for connecting Mattik to Manchester bassline references.'),
('bassline', 'Mattik', 'Soundboy Murda', 'Mattik Music', null, null, '2024-06-21', 439, 'United Kingdom', 'Manchester', 'Mattik is a Manchester-linked UK club producer useful for modern UK Garage, 2-step and bassline discovery.', 'UK Garage / 2-step garage / bassline', 'Use Mattik when the listener wants swinging UKG drums, elastic low end and a modern underground garage feel.', 'https://www.deezer.com/track/2863750312', 'https://www.deezer.com/track/2863750312', '2863750312', 'https://www.deezer.com/track/2863750312', 'https://cdn-images.dzcdn.net/images/cover/81ecb86de5e81538fcb0b7d9f9ca28ba/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Mattik+Soundboy+Murda', null, null, null, null, 'https://mattikmusic.bandcamp.com;https://soundcloud.com/search?q=Mattik;https://www.instagram.com/explore/search/keyword/?q=Mattik', 'bassline;uk_garage;soundboy;modern_ukg;mattik_depth', 'Soundboy Murda;Mattik;UK Garage;bassline', 'soundsystem_bassline', 'mattik_depth', 'published', 'medium_high', 'Exact Deezer artist/track match; added to prevent Bubble from being a single-track profile.'),
('uk_garage', 'Sammy Virji', 'If U Need It', null, null, null, '2023-11-03', 179, 'United Kingdom', null, 'Sammy Virji is a core modern UK Garage reference with bright swing and accessible club pressure.', 'UK Garage / bassline / UK funky', 'Use as a clean modern UKG bridge after Mattik.', 'https://www.deezer.com/track/2516525761', 'https://www.deezer.com/track/2516525761', '2516525761', 'https://www.deezer.com/track/2516525761', 'https://cdn-images.dzcdn.net/images/cover/46e3bc5f8b650454c205803bdc65cd29/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Sammy+Virji+If+U+Need+It', null, null, null, null, null, 'uk_garage;2_step_garage;modern_ukg;adjacent_to_mattik', 'If U Need It;Sammy Virji;modern UKG', 'bright_ukg_swing', 'adjacent_anchor', 'published', 'high', 'Exact Deezer artist/track match; adjacent artist added to avoid overfitting Mattik only.'),
('uk_garage', 'Sammy Virji', 'Find My Way Home', null, null, null, '2018-12-12', 258, 'United Kingdom', null, 'Sammy Virji is a core modern UK Garage reference with bright swing and accessible club pressure.', 'UK Garage / bassline / UK funky', 'Use as a clean modern UKG bridge after Mattik.', 'https://www.deezer.com/track/883297722', 'https://www.deezer.com/track/883297722', '883297722', 'https://www.deezer.com/track/883297722', 'https://cdn-images.dzcdn.net/images/cover/426f40de64bb183af62e84c56cbdff3a/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Sammy+Virji+Find+My+Way+Home', null, null, null, null, null, 'uk_garage;modern_ukg;2_step_garage;adjacent_to_mattik', 'Find My Way Home;Sammy Virji;UKG', 'melodic_ukg_bounce', 'adjacent_depth', 'published', 'high', 'Exact Deezer artist/track match.'),
('uk_garage', 'Oppidan', 'MR. SANDMAN', null, null, null, '2024-01-26', 145, 'United Kingdom', null, 'Oppidan adds a sharp new-school UK Garage signal for fast, playful club recommendations.', 'UK Garage / bassline', 'Use for short, punchy, new-school UKG after Mattik or Sammy Virji.', 'https://www.deezer.com/track/2596522642', 'https://www.deezer.com/track/2596522642', '2596522642', 'https://www.deezer.com/track/2596522642', 'https://cdn-images.dzcdn.net/images/cover/c81d22543bbf22431a5a427e5d79725d/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Oppidan+MR.+SANDMAN', null, null, null, null, null, 'uk_garage;2_step_garage;modern_ukg;bassline;adjacent_to_mattik', 'MR. SANDMAN;Oppidan;UKG', 'punchy_modern_ukg', 'adjacent_anchor', 'published', 'high', 'Exact Deezer artist/track match.'),
('uk_garage', 'Eliza Rose', 'B.O.T.A. (Baddest Of Them All)', null, null, null, '2022-08-12', 358, 'United Kingdom', null, 'Eliza Rose bridges vocal hooks, UK club swing and the Interplanetary Criminal UKG lane.', 'UK Garage / house / bassline', 'Use as a vocal UKG crossover reference with Interplanetary Criminal signal in metadata.', 'https://www.deezer.com/track/1862856457', 'https://www.deezer.com/track/1862856457', '1862856457', 'https://www.deezer.com/track/1862856457', 'https://cdn-images.dzcdn.net/images/cover/be372a6957e4a9ecfc0cf59347c7968f/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Eliza+Rose+B.O.T.A.+%28Baddest+Of+Them+All%29', null, null, null, null, null, 'uk_garage;vocal_ukg;interplanetary_criminal;club_crossover', 'B.O.T.A.;Baddest Of Them All;Eliza Rose;Interplanetary Criminal;UKG', 'vocal_ukg_crossover', 'adjacent_crossover', 'published', 'high', 'Deezer primary artist is Eliza Rose; Interplanetary Criminal is kept as metadata signal to avoid artist mismatch in preview refresh.'),
('uk_garage', 'Conducta', 'Whippet', null, null, null, '2019-09-20', 258, 'United Kingdom', null, 'Conducta is a key modern UK Garage producer and label-builder; useful for clean 2-step pressure.', 'UK Garage / 2-step', 'Use when Mattik points toward crisp drums, swing and clean club engineering.', 'https://www.deezer.com/track/755452532', 'https://www.deezer.com/track/755452532', '755452532', 'https://www.deezer.com/track/755452532', 'https://cdn-images.dzcdn.net/images/cover/41c0cc4a592e11793b20624f4d3a050d/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Conducta+Whippet', null, null, null, null, null, 'uk_garage;2_step_garage;modern_ukg;adjacent_to_mattik', 'Whippet;Conducta;UK Garage', 'clean_2step_roll', 'adjacent_anchor', 'published', 'high', 'Exact Deezer artist/track match.'),
('uk_garage', 'MJ Cole', 'Sincere (Re-Cue''D)', null, 132.51, null, '2018-11-09', 337, 'United Kingdom', null, 'MJ Cole is a foundational UK Garage reference for melodic 2-step and soulful club writing.', 'UK Garage / 2-step', 'Use as a classic UKG anchor for melodic swing and 2-step history.', 'https://www.deezer.com/track/579927262', 'https://www.deezer.com/track/579927262', '579927262', 'https://www.deezer.com/track/579927262', 'https://cdn-images.dzcdn.net/images/cover/0f6876e2f5cc8e3fa8c75069c174992f/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=MJ+Cole+Sincere+%28Re-Cue%27D%29', null, null, null, null, null, 'uk_garage;2_step_garage;classic_ukg;melodic_ukg', 'Sincere;MJ Cole;UK Garage;2-step', 'classic_soulful_ukg', 'classic_anchor', 'published', 'medium_high', 'Exact Deezer artist/track variant; title kept explicit to avoid confusing it with the original mix.'),
('uk_garage', 'Wookie', 'Battle', null, 130.01, null, '2017-09-29', 300, 'United Kingdom', null, 'Wookie anchors the classic UK Garage and 2-step lane with deep swing and bass pressure.', 'UK Garage / 2-step', 'Use as a classic 2-step anchor when modern UKG likes need roots context.', 'https://www.deezer.com/track/402695832', 'https://www.deezer.com/track/402695832', '402695832', 'https://www.deezer.com/track/402695832', 'https://cdn-images.dzcdn.net/images/cover/b647a53e64371893dd6cecd60141fda9/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Wookie+Battle', null, null, null, null, null, 'uk_garage;2_step_garage;classic_ukg;roots_context', 'Battle;Wookie;UK Garage;2-step', 'classic_2step_bass', 'classic_anchor', 'published', 'high', 'Exact Deezer artist/track match.'),
('uk_garage', 'Artful Dodger', 'Re-Rewind (The Crowd Say Bo Selecta) (feat. Craig David) (Radio Edit)', null, null, null, '1999-11-29', 240, 'United Kingdom', null, 'Artful Dodger is a classic UK Garage reference for vocal 2-step crossover.', 'UK Garage / 2-step', 'Use as a familiar roots checkpoint for vocal UK Garage.', 'https://www.deezer.com/track/2787097302', 'https://www.deezer.com/track/2787097302', '2787097302', 'https://www.deezer.com/track/2787097302', 'https://cdn-images.dzcdn.net/images/cover/dd47d8df4fa2b94e03b322a3ae7e180c/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Artful+Dodger+Re-Rewind+%28The+Crowd+Say+Bo+Selecta%29+%28feat.+Craig+David%29+%28Radio+Edit%29', null, null, null, null, null, 'uk_garage;2_step_garage;classic_ukg;vocal_ukg', 'Re-Rewind;Artful Dodger;Craig David;UK Garage', 'classic_vocal_ukg', 'classic_crossover', 'published', 'high', 'Exact Deezer artist/track match; long title preserved for strict matching.'),
('uk_garage', 'Y U QT', 'Y''all Ready For Dis', null, null, null, '2023-06-02', 197, 'United Kingdom', null, 'Y U QT adds playful rave-facing UK Garage for modern high-energy recommendations.', 'UK Garage / rave garage', 'Use for fun, bright, rave-adjacent UKG after Mattik or Oppidan.', 'https://www.deezer.com/track/2300217585', 'https://www.deezer.com/track/2300217585', '2300217585', 'https://www.deezer.com/track/2300217585', 'https://cdn-images.dzcdn.net/images/cover/3b5b2b77e4794fe7b6e344c86af2ab94/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Y+U+QT+Y%27all+Ready+For+Dis', null, null, null, null, null, 'uk_garage;rave_garage;modern_ukg;adjacent_to_mattik', 'Y''all Ready For Dis;Y U QT;UKG;rave garage', 'rave_ukg_fun', 'adjacent_depth', 'published', 'high', 'Exact Deezer artist/track match.'),
('uk_garage', 'Champion', 'Motherboard', null, null, null, '2011-05-16', 226, 'United Kingdom', null, 'Champion is useful for UK Funky, UKG and bassline-adjacent club recommendations.', 'UK Garage / UK funky / bassline adjacent', 'Use as a bridge from UKG into UK funky and bass pressure without leaving bass music.', 'https://www.deezer.com/track/12694734', 'https://www.deezer.com/track/12694734', '12694734', 'https://www.deezer.com/track/12694734', 'https://cdn-images.dzcdn.net/images/cover/200c70371d6493354db5fdbf3c2bb842/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Champion+Motherboard', null, null, null, null, null, 'uk_garage;uk_funky;bassline_adjacent;club_bass', 'Motherboard;Champion;UK Funky;UK Garage', 'uk_funky_bass_bridge', 'adjacent_bridge', 'published', 'medium_high', 'Exact Deezer artist/track match; mapped to uk_garage because Deezer BPM sits at the lower edge for bassline.'),
('bassline', 'Flava D', 'Mesmerise', null, null, null, '2020-02-14', 270, 'United Kingdom', null, 'Flava D bridges UK Garage, bassline and house with direct club utility.', 'Bassline / UK Garage / house', 'Use for heavier bassline swing and UK club energy around Mattik.', 'https://www.deezer.com/track/2255642677', 'https://www.deezer.com/track/2255642677', '2255642677', 'https://www.deezer.com/track/2255642677', 'https://cdn-images.dzcdn.net/images/cover/e5555034e24836a5e9b5ab38234e6f41/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Flava+D+Mesmerise', null, null, null, null, null, 'bassline;uk_garage;uk_bass;club_bass;adjacent_to_mattik', 'Mesmerise;Flava D;bassline;UKG', 'bassline_club_swing', 'adjacent_anchor', 'published', 'high', 'Exact Deezer artist/track match.'),
('uk_garage', 'MPH', 'Doubt', null, null, null, '2023-02-03', 205, 'United Kingdom', null, 'MPH is a modern UKG and bassline producer useful for clean, fast club recommendations.', 'UK Garage / bassline', 'Use as a precise modern UKG adjacent after Mattik.', 'https://www.deezer.com/track/2318014815', 'https://www.deezer.com/track/2318014815', '2318014815', 'https://www.deezer.com/track/2318014815', 'https://cdn-images.dzcdn.net/images/cover/ad2b9060ca24b88dd62432904090db76/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=MPH+Doubt', null, null, null, null, null, 'uk_garage;modern_ukg;bassline;adjacent_to_mattik', 'Doubt;MPH;132.00FM;UKG', 'tight_modern_ukg', 'adjacent_anchor', 'published', 'high', 'Exact Deezer artist/track match.'),
('uk_garage', 'Main Phase', 'Hear Them', null, null, null, '2021-12-03', 396, 'Denmark', null, 'Main Phase adds deeper rolling UK Garage and dubwise bass music context.', 'UK Garage / dubwise bass / 2-step', 'Use when Mattik points to deeper, rolling, less pop-facing UKG.', 'https://www.deezer.com/track/1544681092', 'https://www.deezer.com/track/1544681092', '1544681092', 'https://www.deezer.com/track/1544681092', 'https://cdn-images.dzcdn.net/images/cover/7294adcf846ec930e643c46ae24a9888/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Main+Phase+Hear+Them', null, null, null, null, null, 'uk_garage;2_step_garage;dubwise;deep_ukg;adjacent_to_mattik', 'Hear Them;Main Phase;Lost City Archives;UK Garage', 'deep_rolling_ukg', 'adjacent_depth', 'published', 'high', 'Exact Deezer artist/track match.'),
('future_garage', 'Joy Orbison', 'Hyph Mngo', null, 140.1, null, '2011-04-04', 338, 'United Kingdom', null, 'Joy Orbison provides post-dubstep/future-garage context around broken rhythm and emotional club pressure.', 'Future garage / post-dubstep / UK bass', 'Use as a future-garage bridge when UKG taste gets more atmospheric and leftfield.', 'https://www.deezer.com/track/90840549', 'https://www.deezer.com/track/90840549', '90840549', 'https://www.deezer.com/track/90840549', 'https://cdn-images.dzcdn.net/images/cover/1222c14b681a338e58398414cc8f2f2a/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Joy+Orbison+Hyph+Mngo', null, null, null, null, null, 'future_garage;post_dubstep;uk_bass;breakbeat_adjacent', 'Hyph Mngo;Joy Orbison;future garage;post-dubstep', 'emotional_broken_club', 'adjacent_bridge', 'published', 'high', 'Exact Deezer artist/track match; future_garage BPM rule widened slightly to keep this canonical edge case valid.'),
('future_garage', 'Burial', 'Archangel', null, 135.11, null, '2014-07-01', 238, 'United Kingdom', null, 'Burial anchors the atmospheric, nocturnal and introspective side of future garage.', 'Future garage / dubstep / ambient garage', 'Use for darker, emotional, late-night garage-adjacent taste.', 'https://www.deezer.com/track/80546728', 'https://www.deezer.com/track/80546728', '80546728', 'https://www.deezer.com/track/80546728', 'https://cdn-images.dzcdn.net/images/cover/5dddd046babf2400103929d94ffca87a/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Burial+Archangel', null, null, null, null, null, 'future_garage;dubstep;ambient_garage;nocturnal', 'Archangel;Burial;Untrue;future garage', 'nocturnal_future_garage', 'classic_anchor', 'published', 'high', 'Exact Deezer artist/track match.'),
('breakbeat', 'Overmono', 'So U Kno', null, null, null, '2021-06-16', 343, 'United Kingdom', null, 'Overmono adds modern UK breakbeat and rave emotion adjacent to garage-informed club taste.', 'Breakbeat / UK bass / techno', 'Use when UKG interest leans toward broken-rave and modern club pressure.', 'https://www.deezer.com/track/2059943407', 'https://www.deezer.com/track/2059943407', '2059943407', 'https://www.deezer.com/track/2059943407', 'https://cdn-images.dzcdn.net/images/cover/728ba9c14c26c60d4bc62af08815cc68/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Overmono+So+U+Kno', null, null, null, null, null, 'breakbeat;uk_bass;garage_adjacent;modern_rave', 'So U Kno;Overmono;breakbeat;UK bass', 'modern_rave_breaks', 'adjacent_bridge', 'published', 'high', 'Exact Deezer artist/track match.'),
('breakbeat', 'Bicep', 'Glue', null, 130.01, null, '2017-08-03', 269, 'United Kingdom', null, 'Bicep anchors emotional breakbeat and UK club crossover for accessible broken-rhythm recommendations.', 'Breakbeat / house / UK club', 'Use when a listener likes broken rhythm but wants something more melodic and emotional.', 'https://www.deezer.com/track/389034231', 'https://www.deezer.com/track/389034231', '389034231', 'https://www.deezer.com/track/389034231', 'https://cdn-images.dzcdn.net/images/cover/81a6151bb6969e916aeac546c61cdf49/1000x1000-000000-80-0-0.jpg', 'https://www.youtube.com/results?search_query=Bicep+Glue', null, null, null, null, null, 'breakbeat;uk_bass;melodic_breaks;garage_adjacent', 'Glue;Bicep;breakbeat;UK club', 'melodic_breakbeat_crossover', 'adjacent_bridge', 'published', 'high', 'Exact Deezer artist/track match.');

insert into public.catalog_artists as catalog_artists (
  style,
  artist,
  country,
  city,
  artist_bio,
  artist_genre,
  artist_profile_hint,
  source,
  source_url,
  status,
  metadata
)
select distinct on (style, artist)
  style,
  artist,
  country,
  city,
  artist_bio,
  artist_genre,
  artist_profile_hint,
  'uk_garage_mattik_bridge_v1_20260704',
  source_url,
  status,
  jsonb_strip_nulls(jsonb_build_object(
    'batch', 'uk_garage_mattik_bridge_v1_20260704',
    'confidence', confidence,
    'bridge_policy', '2_step_as_metadata_keep_existing_uk_garage_style',
    'source_tags', case when coalesce(source_tags, '') = '' then array[]::text[] else string_to_array(source_tags, ';') end,
    'album_keywords', case when coalesce(album_keywords, '') = '' then array[]::text[] else string_to_array(album_keywords, ';') end,
    'label_links', case when coalesce(label_links, '') = '' then array[]::text[] else string_to_array(label_links, ';') end,
    'social_discovery_links', case when coalesce(social_discovery_links, '') = '' then array[]::text[] else string_to_array(social_discovery_links, ';') end,
    'energy_band', energy_band,
    'catalog_role', catalog_role,
    'cover_art_url', cover_art_url,
    'deezer_track_id', deezer_track_id,
    'deezer_track_url', deezer_track_url,
    'youtube_track_url', youtube_track_url,
    'soundcloud_track_url', soundcloud_track_url,
    'bandcamp_track_url', bandcamp_track_url,
    'source_note', source_note
  ))
from uk_garage_mattik_bridge_v1_tracks
order by style, artist, confidence desc
on conflict (style, artist_key) do update set
  country = coalesce(excluded.country, catalog_artists.country),
  city = coalesce(excluded.city, catalog_artists.city),
  artist_bio = excluded.artist_bio,
  artist_genre = excluded.artist_genre,
  artist_profile_hint = excluded.artist_profile_hint,
  source = excluded.source,
  source_url = excluded.source_url,
  status = excluded.status,
  metadata = coalesce(catalog_artists.metadata, '{}'::jsonb) || excluded.metadata,
  updated_at = now();

insert into public.catalog_tracks as catalog_tracks (
  style,
  artist,
  song,
  label,
  bpm_exact,
  preview_url,
  release_date,
  duration_sec,
  country,
  city,
  artist_bio,
  artist_genre,
  artist_profile_hint,
  source,
  source_url,
  status,
  metadata
)
select
  style,
  artist,
  song,
  label,
  bpm_exact,
  preview_url,
  release_date,
  duration_sec,
  country,
  city,
  artist_bio,
  artist_genre,
  artist_profile_hint,
  'uk_garage_mattik_bridge_v1_20260704',
  track_url,
  status,
  jsonb_strip_nulls(jsonb_build_object(
    'batch', 'uk_garage_mattik_bridge_v1_20260704',
    'confidence', confidence,
    'bridge_policy', '2_step_as_metadata_keep_existing_uk_garage_style',
    'deezer_track_id', deezer_track_id,
    'deezer_track_url', deezer_track_url,
    'cover_art_url', cover_art_url,
    'youtube_track_url', youtube_track_url,
    'soundcloud_track_url', soundcloud_track_url,
    'bandcamp_track_url', bandcamp_track_url,
    'bandcamp_track_id', bandcamp_track_id,
    'track_url', track_url,
    'label_links', case when coalesce(label_links, '') = '' then array[]::text[] else string_to_array(label_links, ';') end,
    'social_discovery_links', case when coalesce(social_discovery_links, '') = '' then array[]::text[] else string_to_array(social_discovery_links, ';') end,
    'source_tags', case when coalesce(source_tags, '') = '' then array[]::text[] else string_to_array(source_tags, ';') end,
    'album_keywords', case when coalesce(album_keywords, '') = '' then array[]::text[] else string_to_array(album_keywords, ';') end,
    'energy_band', energy_band,
    'catalog_role', catalog_role,
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['deezer_track_id'],
    'source_note', source_note
  ))
from uk_garage_mattik_bridge_v1_tracks
on conflict (style, track_key) do update set
  label = excluded.label,
  bpm_exact = excluded.bpm_exact,
  preview_url = excluded.preview_url,
  release_date = excluded.release_date,
  duration_sec = coalesce(excluded.duration_sec, catalog_tracks.duration_sec),
  country = coalesce(excluded.country, catalog_tracks.country),
  city = coalesce(excluded.city, catalog_tracks.city),
  artist_bio = excluded.artist_bio,
  artist_genre = excluded.artist_genre,
  artist_profile_hint = excluded.artist_profile_hint,
  source = excluded.source,
  source_url = excluded.source_url,
  status = excluded.status,
  metadata = coalesce(catalog_tracks.metadata, '{}'::jsonb) || excluded.metadata,
  updated_at = now();

commit;
