-- Sonic Search - Varazslo / Absurdus / Varasurdum playable focus.
-- Generated 2026-06-22.
-- Run after supabase/migrations/20260619024500_catalog_extra.sql.

insert into public.catalog_artists as catalog_artists (
  style,
  artist,
  country,
  city,
  artist_bio,
  artist_genre,
  artist_profile_hint,
  source,
  source_url,
  status,
  metadata
) values
(
  'psycore',
  'Varazslo',
  'Hungary',
  null,
  'Varazslo, also found as Varazlo in lineups, is a Hungarian high-BPM psycore/darkpsy project with playable public tracks.',
  'psycore / darkpsy / high-BPM psychedelic trance',
  'Recommend Varazslo in psycore and high-speed darkpsy lanes; do not flatten these tracks into generic dark_psy.',
  'varazslo_absurdus_focus_20260622',
  'https://www.deezer.com/artist/9791434',
  'published',
  jsonb_build_object(
    'batch', 'varazslo_absurdus_focus_20260622',
    'source_file', 'data/varazslo_absurdus_playable_tracks_20260622.csv',
    'confidence', 'high',
    'aliases', array['Varazlo', 'Varazslo Music'],
    'catalog_role', 'artist_focus_anchor',
    'future_event', jsonb_build_object(
      'name', 'Existance Festival 2026',
      'date', '2026-09-03',
      'source_url', 'https://www.skiddle.com/festivals/existance-festival/'
    )
  )
),
(
  'dark_psy',
  'Absurdus',
  'Hungary',
  null,
  'Absurdus is kept as a darkpsy/night psytrance project with its own playable tracks, separate from the Varasurdum collaboration.',
  'darkpsy / night psytrance',
  'Recommend Absurdus in dark_psy/night psy; do not promote to hitech or psycore without stronger BPM or release evidence.',
  'varazslo_absurdus_focus_20260622',
  'https://www.deezer.com/artist/1235794',
  'published',
  jsonb_build_object(
    'batch', 'varazslo_absurdus_focus_20260622',
    'source_file', 'data/varazslo_absurdus_playable_tracks_20260622.csv',
    'confidence', 'high',
    'aliases', array['Abusurdus'],
    'catalog_role', 'artist_focus_anchor',
    'future_event', jsonb_build_object(
      'name', 'Existance Festival 2026',
      'date', '2026-09-03',
      'source_url', 'https://www.skiddle.com/festivals/existance-festival/'
    )
  )
),
(
  'psycore',
  'Varasurdum',
  'Hungary',
  null,
  'Varasurdum is the Varazslo x Absurdus collaborative project, kept separate because Mechanika has a public playable URL.',
  'darkpsy / psycore live collaboration',
  'Recommend Varasurdum as the collaborative project rather than duplicating it as a DJ-only alias.',
  'varazslo_absurdus_focus_20260622',
  'https://www.youtube.com/watch?v=B6S2o7sCIj8',
  'published',
  jsonb_build_object(
    'batch', 'varazslo_absurdus_focus_20260622',
    'source_file', 'data/varazslo_absurdus_playable_tracks_20260622.csv',
    'confidence', 'medium_high',
    'aliases', array['Varazslo x Absurdus', 'Varazslo vs Absurdus'],
    'catalog_role', 'collab_project_with_public_track',
    'future_event', jsonb_build_object(
      'name', 'Existance Festival 2026',
      'date', '2026-09-03',
      'source_url', 'https://www.skiddle.com/festivals/existance-festival/'
    )
  )
)
on conflict (style, artist_key) do update set
  country = coalesce(excluded.country, catalog_artists.country),
  city = coalesce(excluded.city, catalog_artists.city),
  artist_bio = coalesce(excluded.artist_bio, catalog_artists.artist_bio),
  artist_genre = coalesce(excluded.artist_genre, catalog_artists.artist_genre),
  artist_profile_hint = coalesce(excluded.artist_profile_hint, catalog_artists.artist_profile_hint),
  source = excluded.source,
  source_url = coalesce(excluded.source_url, catalog_artists.source_url),
  status = case when catalog_artists.status = 'hidden' then catalog_artists.status else excluded.status end,
  metadata = coalesce(catalog_artists.metadata, '{}'::jsonb) || excluded.metadata,
  updated_at = now();

insert into public.catalog_tracks as catalog_tracks (
  style,
  artist,
  song,
  label,
  bpm_exact,
  preview_url,
  release_date,
  duration_sec,
  country,
  city,
  artist_bio,
  artist_genre,
  artist_profile_hint,
  source,
  source_url,
  status,
  metadata
) values
(
  'psycore',
  'Varazslo',
  'Taltos',
  'SoundCloud / Underground',
  198,
  null,
  '2015-01-01',
  450,
  'Hungary',
  null,
  'Varazslo, also found as Varazlo in lineups, is a Hungarian high-BPM psycore/darkpsy project with playable public tracks.',
  'psycore / darkpsy / high-BPM psychedelic trance',
  'SoundCloud direct URL makes this a playable psycore anchor for Varazslo.',
  'varazslo_absurdus_focus_20260622',
  'https://soundcloud.com/varazslo/varazslo-taltos?in=rpmota/sets/psycore',
  'published',
  jsonb_build_object(
    'batch', 'varazslo_absurdus_focus_20260622',
    'source_file', 'data/varazslo_absurdus_playable_tracks_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['soundcloud_embed'],
    'soundcloud_track_url', 'https://soundcloud.com/varazslo/varazslo-taltos?in=rpmota/sets/psycore',
    'source_tags', array['psycore', 'darkpsy', 'varazslo', 'varazlo', 'high_bpm'],
    'catalog_role', 'artist_focus_anchor',
    'confidence', 'high'
  )
),
(
  'psycore',
  'Varazslo',
  'Hall of Purity',
  'Voodoo Hoodoo Recordings',
  null,
  'https://cdnt-preview.dzcdn.net/api/1/1/c/7/2/0/c72817bdad8db0b07c9d2128522121aa.mp3?hdnea=exp=1782107589~acl=/api/1/1/c/7/2/0/c72817bdad8db0b07c9d2128522121aa.mp3*~data=user_id=0,application_id=42~hmac=c77ee9d657b1ef6ecb50a06d7dd44636367edc8511dfef3112ecc04c31ff11cd',
  '2022-06-04',
  452,
  'Hungary',
  null,
  'Varazslo is a Hungarian high-BPM psycore/darkpsy project with playable public tracks.',
  'psycore / darkpsy / high-BPM psychedelic trance',
  'Deezer confirms the track and gives a playable preview; keep in psycore.',
  'varazslo_absurdus_focus_20260622',
  'https://www.deezer.com/track/1767007297',
  'published',
  jsonb_build_object(
    'batch', 'varazslo_absurdus_focus_20260622',
    'source_file', 'data/varazslo_absurdus_playable_tracks_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['audio_preview'],
    'deezer_track_id', '1767007297',
    'deezer_track_url', 'https://www.deezer.com/track/1767007297',
    'source_tags', array['psycore', 'darkpsy', 'varazslo', 'varazlo'],
    'catalog_role', 'artist_focus_anchor',
    'confidence', 'high'
  )
),
(
  'psycore',
  'Varazslo',
  'Information',
  'Zenovoid Records',
  null,
  'https://cdnt-preview.dzcdn.net/api/1/1/f/9/8/0/f986a9638af2b7cc7d8de25a7998ef50.mp3?hdnea=exp=1782107589~acl=/api/1/1/f/9/8/0/f986a9638af2b7cc7d8de25a7998ef50.mp3*~data=user_id=0,application_id=42~hmac=55342d7bd7fb323ce09a85b0945ce653876bbe41286d60ab5f04efedf369cf91',
  '2021-11-28',
  780,
  'Hungary',
  null,
  'Varazslo is a Hungarian high-BPM psycore/darkpsy project with playable public tracks.',
  'psycore / darkpsy / high-BPM psychedelic trance',
  'Deezer confirms the track and gives a playable preview; keep in psycore.',
  'varazslo_absurdus_focus_20260622',
  'https://www.deezer.com/track/1597215172',
  'published',
  jsonb_build_object(
    'batch', 'varazslo_absurdus_focus_20260622',
    'source_file', 'data/varazslo_absurdus_playable_tracks_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['audio_preview'],
    'deezer_track_id', '1597215172',
    'deezer_track_url', 'https://www.deezer.com/track/1597215172',
    'source_tags', array['psycore', 'darkpsy', 'varazslo', 'varazlo'],
    'catalog_role', 'artist_focus_anchor',
    'confidence', 'high'
  )
),
(
  'psycore',
  'Varazslo',
  'Promised Land',
  'Voodoo Hoodoo Recordings',
  null,
  'https://cdnt-preview.dzcdn.net/api/1/1/e/c/a/0/eca385a30576cfa5a9c823d0185079f0.mp3?hdnea=exp=1782107589~acl=/api/1/1/e/c/a/0/eca385a30576cfa5a9c823d0185079f0.mp3*~data=user_id=0,application_id=42~hmac=17ea3f2e09ff3e771164b59a3539aa972fdc0ac7ed880afc926591697018e246',
  '2022-06-04',
  521,
  'Hungary',
  null,
  'Varazslo is a Hungarian high-BPM psycore/darkpsy project with playable public tracks.',
  'psycore / darkpsy / high-BPM psychedelic trance',
  'Deezer confirms the track and gives a playable preview; keep in psycore.',
  'varazslo_absurdus_focus_20260622',
  'https://www.deezer.com/track/1767007317',
  'published',
  jsonb_build_object(
    'batch', 'varazslo_absurdus_focus_20260622',
    'source_file', 'data/varazslo_absurdus_playable_tracks_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['audio_preview'],
    'deezer_track_id', '1767007317',
    'deezer_track_url', 'https://www.deezer.com/track/1767007317',
    'source_tags', array['psycore', 'darkpsy', 'varazslo', 'varazlo'],
    'catalog_role', 'artist_focus_anchor',
    'confidence', 'high'
  )
),
(
  'psycore',
  'Varazslo',
  'Turan',
  'Zenovoid Records',
  null,
  'https://cdnt-preview.dzcdn.net/api/1/1/5/4/4/0/544963e8a69af44944893e6d5267c7f9.mp3?hdnea=exp=1782107590~acl=/api/1/1/5/4/4/0/544963e8a69af44944893e6d5267c7f9.mp3*~data=user_id=0,application_id=42~hmac=8936e0c917539885aee9b2a56e16b0748a05050fa9fcc87a289d74525dd80047',
  '2025-08-24',
  382,
  'Hungary',
  null,
  'Varazslo is a Hungarian high-BPM psycore/darkpsy project with playable public tracks.',
  'psycore / darkpsy / high-BPM psychedelic trance',
  'Deezer confirms the track and gives a playable preview; keep in psycore.',
  'varazslo_absurdus_focus_20260622',
  'https://www.deezer.com/track/3523326601',
  'published',
  jsonb_build_object(
    'batch', 'varazslo_absurdus_focus_20260622',
    'source_file', 'data/varazslo_absurdus_playable_tracks_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['audio_preview'],
    'deezer_track_id', '3523326601',
    'deezer_track_url', 'https://www.deezer.com/track/3523326601',
    'source_tags', array['psycore', 'darkpsy', 'varazslo', 'varazlo'],
    'catalog_role', 'artist_focus_anchor',
    'confidence', 'high'
  )
),
(
  'dark_psy',
  'Absurdus',
  'Transmutation',
  'Don''t Try This at Home',
  null,
  'https://cdnt-preview.dzcdn.net/api/1/1/5/3/f/0/53f18fd13d1d90576a635a8d408bd60f.mp3?hdnea=exp=1782107588~acl=/api/1/1/5/3/f/0/53f18fd13d1d90576a635a8d408bd60f.mp3*~data=user_id=0,application_id=42~hmac=c500e969b054a4131398e870ea48079595fb7efcd7c68686ec0cf65cdcf52c23',
  '2025-09-01',
  573,
  'Hungary',
  null,
  'Absurdus is kept as a darkpsy/night psytrance project with its own playable tracks.',
  'darkpsy / night psytrance',
  'Keep Absurdus in dark_psy/night psy; do not promote to psycore or hitech without stronger evidence.',
  'varazslo_absurdus_focus_20260622',
  'https://www.deezer.com/track/3528600411',
  'published',
  jsonb_build_object(
    'batch', 'varazslo_absurdus_focus_20260622',
    'source_file', 'data/varazslo_absurdus_playable_tracks_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['audio_preview'],
    'deezer_track_id', '3528600411',
    'deezer_track_url', 'https://www.deezer.com/track/3528600411',
    'source_tags', array['darkpsy', 'night_psy', 'absurdus', 'abusurdus', 'varasurdum_related'],
    'catalog_role', 'artist_focus_anchor',
    'confidence', 'high'
  )
),
(
  'dark_psy',
  'Absurdus',
  'Zephyrum',
  'As Deep as Possible',
  null,
  'https://cdnt-preview.dzcdn.net/api/1/1/c/a/c/0/cac7b2274fb7c3aa300bd54b47cec895.mp3?hdnea=exp=1782107588~acl=/api/1/1/c/a/c/0/cac7b2274fb7c3aa300bd54b47cec895.mp3*~data=user_id=0,application_id=42~hmac=4631caceff59b5a9301fe35e553626d6d2b123eda115531fced570f2d2a0519d',
  '2026-04-18',
  474,
  'Hungary',
  null,
  'Absurdus is kept as a darkpsy/night psytrance project with its own playable tracks.',
  'darkpsy / night psytrance',
  'Keep Absurdus in dark_psy/night psy; do not promote to psycore or hitech without stronger evidence.',
  'varazslo_absurdus_focus_20260622',
  'https://www.deezer.com/track/3930295991',
  'published',
  jsonb_build_object(
    'batch', 'varazslo_absurdus_focus_20260622',
    'source_file', 'data/varazslo_absurdus_playable_tracks_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['audio_preview'],
    'deezer_track_id', '3930295991',
    'deezer_track_url', 'https://www.deezer.com/track/3930295991',
    'source_tags', array['darkpsy', 'night_psy', 'absurdus', 'abusurdus', 'varasurdum_related'],
    'catalog_role', 'artist_focus_anchor',
    'confidence', 'high'
  )
),
(
  'psycore',
  'Varasurdum',
  'Mechanika',
  'YouTube / Zenovoid Records',
  null,
  null,
  null,
  null,
  'Hungary',
  null,
  'Varasurdum is the Varazslo x Absurdus collaborative project with a public playable URL.',
  'darkpsy / psycore live collaboration',
  'Keep Varasurdum separate from both solo projects because Mechanika is playable under the collaboration.',
  'varazslo_absurdus_focus_20260622',
  'https://www.youtube.com/watch?v=B6S2o7sCIj8',
  'published',
  jsonb_build_object(
    'batch', 'varazslo_absurdus_focus_20260622',
    'source_file', 'data/varazslo_absurdus_playable_tracks_20260622.csv',
    'playback_policy', 'published_requires_in_app_playback',
    'playable_sources', array['youtube_embed'],
    'youtube_track_url', 'https://www.youtube.com/watch?v=B6S2o7sCIj8',
    'source_tags', array['psycore', 'darkpsy', 'varasurdum', 'varazslo_absurdus', 'collaboration'],
    'catalog_role', 'collab_project_with_public_track',
    'confidence', 'medium_high'
  )
)
on conflict (style, track_key) do update set
  label = coalesce(excluded.label, catalog_tracks.label),
  bpm_exact = coalesce(excluded.bpm_exact, catalog_tracks.bpm_exact),
  preview_url = coalesce(excluded.preview_url, catalog_tracks.preview_url),
  release_date = coalesce(excluded.release_date, catalog_tracks.release_date),
  duration_sec = coalesce(excluded.duration_sec, catalog_tracks.duration_sec),
  country = coalesce(excluded.country, catalog_tracks.country),
  city = coalesce(excluded.city, catalog_tracks.city),
  artist_bio = coalesce(excluded.artist_bio, catalog_tracks.artist_bio),
  artist_genre = coalesce(excluded.artist_genre, catalog_tracks.artist_genre),
  artist_profile_hint = coalesce(excluded.artist_profile_hint, catalog_tracks.artist_profile_hint),
  source = excluded.source,
  source_url = coalesce(excluded.source_url, catalog_tracks.source_url),
  status = case when catalog_tracks.status = 'hidden' then catalog_tracks.status else excluded.status end,
  metadata = coalesce(catalog_tracks.metadata, '{}'::jsonb) || excluded.metadata,
  updated_at = now();
